#!/usr/bin/env python

# Renames /ublox_gps/fix messages to /fix messages

import rospy
from sensor_msgs.msg import NavSatFix

navsat_pub = rospy.Publisher('/fix', NavSatFix, queue_size=10)


def navsat_callback(navsat_msg):
    rospy.logwarn("\n\n\n\n\n\n\nPublishing navsat_msg\n\n\n\n\n\n\n", *args)
    navsat_pub.publish(navsat_msg)

if __name__ == '__main__':
    rospy.init_node('fix_translator', anonymous=True)
    navsat_sub = rospy.Subscriber("/ublox_gps/fix", NavSatFix, navsat_callback)
    rospy.spin()
