# Configuration Settings for ZED-F9P device

debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM0
frame_id: gps

use_adr: true

nav_rate: 1

uart1:
  baudrate: 460800

# Enable u-blox message publishers
publish:
  all: true
  esf:
    meas: true
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true

